// EXPORT DATAS
export const questionPack = [
  {
    id: 'A1',
    question: 'Confiance',
    description: 'Doit-on faire confiance ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok', 'Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher', 'Balti'],
  },
  {
    id: 'B2',
    question: 'Conflit',
    description: 'Doit-on éviter les conflits ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Bellagher', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok', 'Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Sinklair'],
  },
  {
    id: 'C3',
    question: 'Discussion',
    description: "L'avis des autres compte-t-il ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Balti', 'Bellagher', 'Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Havok'],
  },
  {
    id: 'D4',
    question: 'Voter',
    description: 'La majorité a-t-elle toujours raison ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Balti', 'Bellagher'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Royce', 'Ferro', 'Sinklair', 'Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein'],
  },
  {
    id: 'E5',
    question: 'Violence',
    description: 'La violence est-elle une solution envisageable ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Royce', 'Ferro', 'Havok'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Bellagher', 'Sinklair'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti'],
  },
  {
    id: 'F6',
    question: 'Ordre',
    description: 'Faut-il toujours respecter les règles ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Royce', 'Sinklair', 'Ferro', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher'],
  },
  {
    id: 'G7',
    question: 'Punition',
    description: 'Nos erreurs doivent-elles toujours être punies ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Royce', 'Sinklair', 'Ferro'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti', 'Bellagher'],
  },
  {
    id: 'H8',
    question: 'Pouvoir',
    description: 'Si vous le pouvez, désirez-vous prendre le Pouvoir ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Royce', 'Ferro'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Havok', 'Sinklair'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti', 'Bellagher'],
  },
  {
    id: 'I9',
    question: 'Mérite',
    description: "Faut-il uniquement obtenir ce que l'on mérite ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Royce', 'Havok', 'Ferro', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Bellagher', 'Sinklair'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein'],
  },
  {
    id: 'J10',
    question: 'Privilège',
    description: "Peut-on avoir des privilèges par rapport à d'autres ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Royce', 'Ferro'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Bellagher', 'Havok', 'Sinklair'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti'],
  },
  {
    id: 'K11',
    question: 'Différence',
    description: 'Les différences sont-elles une force ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Bellagher', 'Havok', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Royce', 'Ferro', 'Sinklair'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein'],
  },
  {
    id: 'L12',
    question: 'Partager',
    description: "Faut-il toujours partager ce que l'on a ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Bellagher', 'Sinklair', 'Havok'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti'],
  },
  {
    id: 'M13',
    question: 'Donner',
    description: 'Faut-il donner à ceux qui ont le moins ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Sinklair', 'Havok'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher', 'Balti'],
  },
  {
    id: 'N14',
    question: 'Pardonner',
    description: 'Faut-il savoir pardonner ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Ferro', 'Royce', 'Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher', 'Balti'],
  },
  {
    id: 'O15',
    question: 'Communauté',
    description: 'Faut-il savoir faire passer le groupe avant soi ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Bellagher'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Royce', 'Ferro', 'Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Sinklair', 'Balti'],
  },
  {
    id: 'P16',
    question: 'Solidarité',
    description: "Faut-il savoir compter sur l'entraide ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Bellagher', 'Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok', 'Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti'],
  },
  {
    id: 'Q17',
    question: 'Egalité',
    description: 'Sommes-nous tous égaux ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Bellagher', 'Havok'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Royce', 'Ferro'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Sinklair', 'Balti'],
  },
  {
    id: 'R18',
    question: 'Fierté',
    description: 'Faut-il être fier en toute circonstances ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Royce', 'Ferro', 'Havok'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Sinklair'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti', 'Bellagher'],
  },
  {
    id: 'S19',
    question: 'Loyauté',
    description: 'Faut-il être loyal ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Royce', 'Sinklair', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Ferro', 'Bellagher'],
  },
  {
    id: 'T20',
    question: 'Responsabilité',
    description: 'Sommes-nous responsables de toutes nos erreurs ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Royce', 'Ferro', 'Balti', 'Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher'],
  },
  {
    id: 'U21',
    question: 'Perfection',
    description: 'La perfection doit-elle être recherchée ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Ferro', 'Sinklair', 'Royce'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Havok', 'Bellagher'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti'],
  },
  {
    id: 'V22',
    question: 'Religion',
    description: 'Les croyances doivent-elles être respectées ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Royce', 'Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Ferro', 'Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Balti', 'Bellagher'],
  },
  {
    id: 'W23',
    question: 'Famille',
    description: "Est-ce important d'être en famille ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Royce', 'Sinklair', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Ferro', 'Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher'],
  },
  {
    id: 'X24',
    question: 'Ecologie',
    description: 'Faut-il préserver la nature à tout prix ?',
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Groupe'],
    pointA: ['Bellagher', 'Sinklair'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Individu'],
    pointB: ['Ferro', 'Royce'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Havok', 'Balti'],
  },
  {
    id: 'Y25',
    question: 'Richesse',
    description: "Faut-il avoir beaucoup d'argent ?",
    reponseA: 'fa-sharp fa-solid fa-thumbs-up',
    society1: ['Individu'],
    pointA: ['Royce', 'Ferro', 'Balti'],
    reponseB: 'fa-sharp fa-solid fa-thumbs-down',
    society2: ['Groupe'],
    pointB: ['Sinklair', 'Havok'],
    reponseC: 'fa-sharp fa-solid fa-equals',
    society3: ['Neutre'],
    pointC: ['Klein', 'Bellagher'],
  },
]

export default questionPack
